name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # change to master if your default branch is master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    concurrency:
      group: github-pages
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          cd swim_parser
          flutter pub get

      - name: Build Web Application
        run: |
          cd swim_parser
          flutter build web --release --base-href "/swim-parser-coach/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: swim_parser/build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
